Repository redhat-performance/jetlag, pull requests merged in 2024-12, with the labels that each got.

#580 Quieter bootstrap
  bootstrap.sh
Labels: enhancement, lgtm, approved, do-not-merge/hold

#582 remove grafana from cluter monitoring config as it's not supported anymore
  ansible/roles/mno-post-cluster-install/templates/cluster-monitoring-config.yml.j2
Labels: lgtm, approved, ok-to-test

#584 Remove Deprecated container image
  ansible/roles/sync-acm-d/tasks/main.yml
  ansible/vars/sync-acm-d.sample.yml
Labels: lgtm, approved
