Repository redhat-performance/jetlag, pull requests merged in 2025-08, with the labels that each got.

#676 Added missing lab variables to MNO (Multi Node Openshift) scale out deployment
  ansible/mno-scale-out.yml
Labels: lgtm, approved

#675 Add Download discovery ISO task retries
  ansible/roles/generate-discovery-iso/tasks/main.yml
Labels: lgtm, approved

#681 Fix wait for nodes to be discovered race condition
  ansible/roles/wait-hosts-discovered/tasks/main.yml
Labels: lgtm, approved

#680 PERFSCALE-4093: Auto configure network interfaces vars
  ansible/roles/create-inventory/tasks/main.yml
  ansible/roles/create-inventory/templates/inventory-mno.j2
  ansible/roles/create-inventory/templates/inventory-sno.j2
  ansible/roles/create-inventory/templates/inventory-vmno.j2
  ansible/vars/all.sample.yml
  docs/tips-and-vars.md
Labels: lgtm, approved, jira/valid-reference

#684 Add perflab r740xd CL-U-2, CL-G-2 install disk by-path to docs table.
  docs/tips-and-vars.md
Labels: documentation, approved

#685 Add scale out functionality for Compact MNO Cluster
  ansible/roles/mno-scale-out-csr/tasks/main.yml
Labels: lgtm, approved
