Repository redhat-performance/jetlag, pull requests merged in 2025-02, with the labels that each got.

#601 More on the OSP disk partition that survives foreman rebuilds
  docs/troubleshooting.md
Labels: approved

#563 Hybrid deployments
  README.md
  ansible/mno-deploy.yml
  ansible/roles/boot-iso/tasks/libvirt.yml
  ansible/roles/boot-iso/tasks/main.yml
  ansible/roles/create-ai-cluster/defaults/main/main.yml
  ansible/roles/create-ai-cluster/tasks/main.yml
  ansible/roles/create-ai-cluster/templates/mac_interface_map.json.j2
  ansible/roles/create-inventory/defaults/main/main.yml
  ansible/roles/create-inventory/templates/inventory-mno.j2
  ansible/roles/mno-post-cluster-install/defaults/main/main.yml
Labels: lgtm, approved

#602 Add to the cnv install note
  ansible/vars/all.sample.yml
  ansible/vars/ibmcloud.sample.yml
  docs/deploy-mno-byol.md
  docs/deploy-mno-ibmcloud.md
  docs/deploy-mno-performancelab.md
  docs/deploy-mno-scalelab.md
  docs/deploy-sno-ibmcloud.md
  docs/deploy-sno-performancelab.md
  docs/deploy-sno-scalelab.md
Labels: approved

#597 Continuing work for #352 (Removing multiple SNO complexity) + split D…
  ansible/roles/create-ai-cluster/tasks/01_manifest_update.yml
  ansible/roles/create-ai-cluster/tasks/main.yml
  ansible/roles/ibmcloud-create-ai-cluster/tasks/main.yml
  ansible/roles/ibmcloud-sno-create-ai-cluster/tasks/01_manifest_task.yml
  ansible/roles/install-cluster/tasks/check-cluster-install.yml
  ansible/roles/sno-create-ai-cluster/tasks/create_individual_sno.yml
  ansible/roles/sno-create-ai-cluster/tasks/du_profile_manifest_tasks.yml
  ansible/roles/sno-create-ai-cluster/tasks/main.yml
  ansible/roles/sno-create-ai-cluster/templates/ibmcloud_mac_interface_map.json.j2
  ansible/roles/sno-create-ai-cluster/templates/ibmcloud_nmstate.yml.j2
  ansible/roles/sno-create-ai-cluster/templates/mac_interface_map.json.j2
  ansible/roles/sno-create-ai-cluster/templates/nmstate.yml.j2
  ansible/roles/sno-post-cluster-install/tasks/du_profile_post_install_tasks.yml
  ansible/roles/sno-post-cluster-install/tasks/main.yml
  ansible/roles/sno-wait-hosts-discovered/tasks/main.yml
  ansible/roles/sno-wait-hosts-discovered/tasks/set_install_disk.yml
  ansible/sno-deploy.yml
Labels: approved

#604 Remove more references to BM instead of MNO
  ansible/mno-post-deploy-add-bmc.yml
  ansible/roles/create-inventory/tasks/main.yml
  ansible/roles/ibmcloud-create-inventory/defaults/main/main.yml
  ansible/roles/mno-add-bmc/tasks/add-bmc-to-bmh.yml
  ansible/roles/mno-add-bmc/tasks/main.yml
  ansible/roles/mno-add-bmc/templates/bmc-secret.yml.j2
  docs/deploy-mno-ibmcloud.md
  docs/deploy-mno-performancelab.md
  docs/deploy-sno-ibmcloud.md
  docs/deploy-sno-performancelab.md
Labels: lgtm, approved

#607 Remove extra ocp_build validation
  ansible/roles/validate-vars/tasks/main.yml
Labels: lgtm, approved

#610 Add tshooting for old VIP in use
  docs/troubleshooting.md
Labels: documentation, lgtm, approved

#606 support CI nightly releases
  ansible/roles/bastion-install/tasks/main.yml
  ansible/roles/bastion-ocp-version/tasks/main.yml
  ansible/roles/ocp-release/defaults/main.yml
  ansible/roles/ocp-release/tasks/main.yml
  docs/deploy-mno-scalelab.md
Labels: lgtm, approved

#612 Removing hybrid_worker_count from non-create inventory roles
  ansible/roles/create-ai-cluster/defaults/main/main.yml
  ansible/roles/mno-post-cluster-install/defaults/main/main.yml
Labels: lgtm, approved

#616 Fix the performancelab private networking table link
  docs/tips-and-vars.md
Labels: lgtm, approved

#615 Add ci to list of `ocp_build_types`
  ansible/roles/validate-vars/defaults/main.yml
Labels: lgtm, approved

#617 Adjust the ocp_build and ocp_version comments and docs
  ansible/vars/all.sample.yml
  ansible/vars/ibmcloud.sample.yml
  docs/deploy-mno-byol.md
  docs/deploy-mno-ibmcloud.md
  docs/deploy-mno-performancelab.md
  docs/deploy-mno-scalelab.md
  docs/deploy-sno-ibmcloud.md
  docs/deploy-sno-performancelab.md
  docs/deploy-sno-scalelab.md
  docs/tips-and-vars.md
Labels: lgtm, approved

#618 Adjust defaults for "hv_vm_prefix" and "unmount_virtual_media_on_error"
  ansible/roles/create-inventory/defaults/main/main.yml
  ansible/roles/install-cluster/defaults/main/main.yml
  docs/hypervisors.md
Labels: lgtm, approved

#619 Public vlan fixes revisited
  ansible/roles/bastion-coredns/templates/resolv.conf.j2
  ansible/roles/bastion-dnsmasq/templates/resolv.conf.j2
  ansible/roles/create-inventory/templates/inventory-mno.j2
  ansible/roles/validate-vars/tasks/main.yml
  ansible/vars/all.sample.yml
  docs/deploy-mno-byol.md
  docs/deploy-mno-performancelab.md
  docs/deploy-mno-scalelab.md
  docs/deploy-sno-performancelab.md
  docs/deploy-sno-scalelab.md
Labels: lgtm, approved

#620 Update the default OCP install to 4.18 now
  ansible/vars/all.sample.yml
  ansible/vars/ibmcloud.sample.yml
  ansible/vars/sync-ocp-release.sample.yml
  docs/deploy-mno-byol.md
  docs/deploy-mno-ibmcloud.md
  docs/deploy-mno-performancelab.md
  docs/deploy-mno-scalelab.md
  docs/deploy-sno-ibmcloud.md
  docs/deploy-sno-performancelab.md
  docs/deploy-sno-scalelab.md
Labels: lgtm, approved
